version: '3.8'

services:
  backend:
    build: ./backend
    container_name: beamforming-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - beamforming-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: beamforming-frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - beamforming-net

networks:
  beamforming-net:
    driver: bridge
